# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Clean deployment folder
      run: |
        ssh -i ~/.ssh/id_ed25519 user@45.141.102.127 "rm -rf /opt/docker/OutAdapter/*"

    - name: Deploy to specific folder
      run: |
        scp -i ~/.ssh/id_ed25519 \
        build/artifacts/*.jar \
        user@45.141.102.127:/opt/docker/OutAdapter

    - name: Deploy application.yml
      run: |
        scp -i ~/.ssh/id_ed25519 \
        application.yml \
        user@45.141.102.127:/opt/docker/OutAdapter/application.yml


    - uses: appleboy/ssh-action@master
      name: Deploy via SSH
      with:
        host: 45.141.102.127
        username: "root"
        password: "0NCwBIrIoX"
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          docker-compose up -d outAdapter

#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
